<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bottom_element</name>
   <tag></tag>
   <elementGuidId>3be3c2d6-b248-48eb-869d-fef5fc286508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.gap-4.align-items-center.justify-content-center.my-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[11]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'd-flex gap-4 align-items-center justify-content-center my-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pagination&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[11]</value>
      <webElementGuid>a030ae42-3cf3-42f3-a3a6-028f7c819f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1.000.000.000.000.000'])[1]/following::div[1]</value>
      <webElementGuid>84e91ce8-4f6e-4188-9bce-7de893fe75a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abc1'])[1]/following::div[1]</value>
      <webElementGuid>49d985f9-56b6-4ee9-9b29-7d3b59b665a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]</value>
      <webElementGuid>9677c2fa-0d54-4f99-9b55-8cdc2b9c9bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '← Previous Next →' or . = '← Previous Next →')]</value>
      <webElementGuid>a5cacede-a0fd-4647-91df-408226ca4314</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
