<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sold_fluid</name>
   <tag></tag>
   <elementGuidId>a9d7f7c6-9c80-4469-86da-35387e449b57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '/empty-product.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d011dfbb-d46b-4bf1-9f17-86cdf77e2a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>2b5d324d-675a-466d-99e2-8c059a4dbf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/empty-product.svg</value>
      <webElementGuid>1ae01369-d867-42b0-8ce9-27acd62c7c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;pt-5 mt-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row my-5&quot;]/div[@class=&quot;col-12 col-lg-9 mt-5 mt-lg-0&quot;]/div[@class=&quot;row g-4&quot;]/div[@class=&quot;d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;container d-flex flex-column justify-content-center align-items-center&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>1c513832-22c6-4db0-9224-164f3a7b42b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>da90a1b8-ab6c-482c-9dba-4be5577bfb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/empty-product.svg']</value>
      <webElementGuid>21d68640-b934-45a6-9407-d4ec4472380b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
